# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-27 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phonenumber', models.CharField(max_length=300)),
                ('emailid', models.CharField(max_length=300)),
                ('loantype', models.CharField(max_length=300)),
            ],
        ),
    ]
