# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-27 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180627_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='requestStatus',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
