# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-21 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankadminDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
                ('mobilenumber', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BankReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendingloan', models.CharField(max_length=300)),
                ('completedloans', models.CharField(max_length=300)),
                ('checkbounce', models.CharField(max_length=300)),
                ('crideitcardlimit', models.CharField(max_length=300)),
                ('crideitcardusage', models.CharField(max_length=300)),
                ('applyingloanconut', models.CharField(max_length=300)),
                ('crideitcardchange', models.CharField(max_length=300)),
            ],
        ),
    ]
