# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-22 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankreport',
            old_name='applyingloanconut',
            new_name='atmusagefine',
        ),
        migrations.RenameField(
            model_name='bankreport',
            old_name='checkbounce',
            new_name='balanceamount',
        ),
        migrations.RenameField(
            model_name='bankreport',
            old_name='completedloans',
            new_name='checkbounch',
        ),
        migrations.RenameField(
            model_name='bankreport',
            old_name='crideitcardchange',
            new_name='complateduration',
        ),
        migrations.RenameField(
            model_name='bankreport',
            old_name='crideitcardlimit',
            new_name='loancount',
        ),
        migrations.RenameField(
            model_name='bankreport',
            old_name='crideitcardusage',
            new_name='loanduration',
        ),
        migrations.RenameField(
            model_name='bankreport',
            old_name='pendingloan',
            new_name='loantype',
        ),
        migrations.AddField(
            model_name='bankreport',
            name='minimambalancefine',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankreport',
            name='modificationfine',
            field=models.CharField(default='exit', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankreport',
            name='paidamount',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
