# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-22 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankadmin', '0002_auto_20180622_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreport',
            name='creditdetails',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
