# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-23 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankadmin', '0004_bankreport_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreport',
            name='duration',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
