# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-27 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankadmin', '0006_bankreport_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankreport',
            name='loantype',
            field=models.CharField(choices=[('personalloan', 'personalloan'), ('farmarloan', 'farmarloan'), ('vatloan', 'vatloan'), ('mortageloan', 'mortageloan'), ('vehicleloan', 'vehicleloan'), ('other', 'other')], max_length=300),
        ),
    ]
